# Site settings
title:       rassemblr 
email:       pdeschen@rassemblr.com 
author:      Pascal Deschenes
description: "Code, ideas, and more."
baseurl:     ""
url:         "http://blog.rassemblr.com"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true 
github_username: pdeschen
twitter_username: pdeschen
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
